services:
  prod:
    build: .
    container_name: jelly_cow_prod
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - jelly_cow_db:/app/db

  dev:
    build: .
    container_name: jelly_cow_dev
    env_file:
      - .env
    volumes:
      - .:/app
      - jelly_cow_db:/app/db
    restart: unless-stopped

volumes:
  jelly_cow_db:
    name: jelly_cow_db
